### ISSUE TITLE
Workflow is failing without json arg

### ISSUE THREAD

**Issue by florianlauer** [South-Paw/action-netlify-cli#3]
Hi,
Just to let you know that your action is falling if you don't pass the `--json` option in the args. I've added you a screenshot to illustrate.
![image](https://github.com/South-Paw/action-netlify-cli/assets/11716644/0850b532-b7e0-492f-a9dc-959ca3384d59)
Cheers
Florian

**Comment by South-Paw** [comment]
Thanks for letting me know, probably just that `fromJson` doesn't work on the empty string when the `--json` flag is omitted.

Might just be as simple as adding an or operator `||` to the action.yml file

The README does mention that "note that the --json flag has been passed when deploying" and the work around is just to add the `--json` flag so I don't really consider this too urgent unless its actively breaking something?

**Comment by florianlauer** [comment]
It's not just the outputs that break, it's the whole step as far as I've tried, I wasn't using the outputs while trying first.
So maybe adding the info that the `--json` flag is required to make everything work should be more visible than a comment in the code example, or if you have any time to make it not fail without it could be even better!

**Comment by leeovery** [comment]
Actually my errors are a little different:

<img width="932" alt="CleanShot 2023-07-26 at 14 57 50@2x" src="https://github.com/South-Paw/action-netlify-cli/assets/1087804/8ed4f402-0f5e-46ae-b878-dfa700a1fd32">

**Comment by leeovery** [comment]
Sorry to triple post. Seems my issues were related to something else on the Netlify end. Not sure what tbh but its working now haha. Its possible that deploying manually got it working again as I hadnt deployed for 2 months due to working on other stuff.

**Comment by South-Paw** [comment]
@leeovery Yeah it looks like the action throws out this kind of error when it can't parse outputs for any reason. I just got it for trying to deploy a non-existent `dir`.

**Comment by leeovery** [comment]
Yea I figured out the same thing a few days ago. My error was typescript wasn't compiling during the build process. The action was suppressing the error so it was hard to track down. 😂

**Comment by South-Paw** [comment]
Yeah I think I'm debugging a similar issue elsewhere as well.

I determined the simplest fix was to remove these outputs - they can still be accessed however, you just need to parse them from the output yourself using `fromJson`. Have [added a recipe to the README](https://github.com/South-Paw/action-netlify-cli#parse---json-flag) for this as well to help others.

Closed by #4
